version: "3"

services:
    app:
        build:
            context: app
            args:
                SECRET_KEY: ${SECRET_KEY}
                SECRET_KEY_SECRET_TOKEN: ${SECRET_KEY_SECRET_TOKEN}
                SECRET_KEY_RESET_PASSWORD_TOKEN: ${SECRET_KEY_RESET_PASSWORD_TOKEN}
                SECRET_KEY_ENCODE_ID: ${SECRET_KEY_ENCODE_ID}
                MAIL_PASSWORD: ${MAIL_PASSWORD}
                DEFAULT_MAIL_SENDER: ${DEFAULT_MAIL_SENDER}
        env_file:
            - .env
        ports:
            - "5000"

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/certs:/etc/nginx/certs:ro
        depends_on:
            - app
        ports:
            - "443:443"
            - "80:80"

